### ISSUE TITLE
Manglende separator i icon classes

### ISSUE THREAD

**Issue by ncjelu** [FSGpilot/frontend-styleguide-components#10]
Det er ikke muligt at bruge ikoner med de indbyggede 'icon-*'-klasser, da stien til billedet ikke er korrekt. 

Jeg kan se i dbwds.css at stierne ser ud til at mangle en separator mellem "svg-icons" og filnavnet, f.eks.:

`
.icon-alert-outline {
  background-image: url("../img/svg-iconsalert-outline.svg");
}
`

**Comment by ncjelu** [comment]
I øvrigt vil jeg lige spørge om det er meningen at mange af ikonerne ikke eksisterer som css-klasser? F.eks. "menu-right.svg"

**Comment by AndersWinther-Dahl** [comment]
Vi har også problemer når vi skal compile med webpack.
Det er i denne fil der skal rettes:
https://github.com/FSGpilot/frontend-styleguide-components/blob/master/src/stylesheets/elements/_icons.scss

Linie 44: background-image: url($icons-folder-path + $icon + ".svg");
rettes til
background-image: url($icons-folder-path +"/" + $icon + ".svg");

**Comment by stil-ux-team** [comment]
Tak for input, vi kigger på det, men vær tålmodig, da vi lige nu samler fejl og rettelser sammen og starter en samlet gennemgang op i løbet af efteråret.

**Comment by stil-ux-team** [comment]
Tak for input, vi kigger på det, men vær tålmodig, da vi lige nu samler fejl og rettelser sammen og starter en samlet gennemgang op i løbet af efteråret.

**Comment by stil-ux-team** [comment]
I skal lige være opmærksomme på, at placeringen for flere svg-ikoner vil ændre sig, da de for nuværende ligger blandet sammen med andre typer filer. Så på sigt vil stien til alle svg-ikoner være /assets/img/svg-icons .

**Comment by AndersWinther-Dahl** [comment]
@stil-ux-team så længe vi bruger de parametre der sættes (/src/stylesheets/core/_variables.scss) så er det vel underordnet hvordan I organiserer det.

**Comment by emiljensengit** [comment]
@AndersWinther-Dahl 
Ah nu ser jeg fejlen.
Jeg har testet med scss-filerne hvor jeg har overskrevet $icons-folder-path med en path som slutter med /, derfor har mine tests virket. Godt fundet. 
@stil-ux-team denne fejl må være en af de første vi får set på når der startes op igen.

**Comment by stil-ux-team** [comment]
@emiljensengit Bestemt. Kan du evt. formulere issuet, så det giver mening for andre også?

**Comment by emiljensengit** [comment]
Et fix er tilføjet i v2.1.2
