### ISSUE TITLE
Stier til borger- og virk-logoer

### ISSUE THREAD

**Issue by AndersWinther-Dahl** [FSGpilot/frontend-styleguide-components#11]
I filerne
```
/src/stylesheets/themes/_virkdk.scss
/src/stylesheets/themes/_borgerdk.scss
```
er der refereret til 
`background-image: url('./../assets/img/logo_virk_indberet.svg');`
`background-image: url('./../assets/img/logo-borgerdk.svg');`

Men der findes ikke en assets-mappe, og derfor fejler vores webpack-compile.
Jeg vil tro at den skal ændres til
`background-image: url('../img/logo_virk_indberet.svg');`

**Comment by stil-ux-team** [comment]
Tak for input, vi kigger på det, men vær tålmodig, da vi lige nu samler fejl og rettelser sammen og starter en samlet gennemgang op i løbet af efteråret.

**Comment by emiljensengit** [comment]
Hej Anders

I mit webpack setup har jeg brugt følgende variable, virker de hos dig?

$font-path:         '~dkwds/src/fonts/IBMPlexSans/';
$image-path:        '~dkwds/src/img';
$site-image-path:   '~dkwds/src/img';
$icons-folder-path: '~dkwds/src/img/svg-icons/';
@import "~dkwds/src/stylesheets/dkwds";

**Comment by emiljensengit** [comment]
Denne er nu fixet i v2.1.2
