### ISSUE TITLE
Å'er mangler ringen i Chrome

### ISSUE THREAD

**Issue by ncjelu** [FSGpilot/frontend-styleguide-components#12]
I tekstfelter mangler der en ring over store å'er. Det ser ud til at højden af form-input er for lille til at rumme det.

Problemet opstår ikke i Firefox, men kan ses i Chrome på Windows, se f.eks. eksemplerne i styleguiden: https://fsgpilot.github.io/frontend-styleguide/designandcode/form-controls. 

Jeg har ikke afprøvet andre browsere.

**Comment by stil-ux-team** [comment]
Tak for fejlmelding. Den er nu oprettet i vores JIRA.

Mvh

**Comment by emiljensengit** [comment]
Et fix er tilføjet i v2.1.2
