### ISSUE TITLE
Link i nav-elementer

### ISSUE THREAD

**Issue by stil-ux-team** [FSGpilot/frontend-styleguide-components#2]
Jeg kan se, at link i fx venstremenuen er sorte, men fremhæves med den blå linkfarve ved :hover. Bør dette ikke skrives ind i afsnittet som link? Det vil helt sikkert afføde spørgsmål ellers.

**Comment by zumouxd** [comment]
Tak for kommentaren. Det var en fejl fra en tidligere iteration. Hover fremhæves med grå farve, og det valgte link i venstremenuen har farveindikation i siden. Håber det svarer på det.
https://fsgpilot.github.io/frontend-styleguide/components/komponenter/sidenav/?s=borgerdk
