### ISSUE TITLE
Backwards compatibility with current Borger.dk

### ISSUE THREAD

**Issue by VisualBean** [FSGpilot/frontend-styleguide-components#22]
Will this be backwards compatible with existing borger.dk sites? or are you breaking ties and going 2.0 so to speak?

**Comment by detfaellesdesignsystem** [comment]
Hi Alex
The new styleguide will not be backwards compatible with existing sites developed using borger.dk's HTML-guide. 
That being said, current sites using the old HTML-guide will not be forced to upgrade to the new stylguide. Only new sites or major re-implementation of existing solutions will have to follow it.

**Comment by VisualBean** [comment]
Awesome! thanks :)
