### ISSUE TITLE
Active-link state, kun som javascript?

### ISSUE THREAD

**Issue by stil-ux-team** [FSGpilot/frontend-styleguide-components#4]
Kunne man overveje en ikke-javascript løsning til at markere active state? Eller er det kun muligt med javascript?

**Comment by emiljensengit** [comment]
Hej John, er det i en specifik komponent at active-state kun kan skiftes via js?
Generelt bliver der ikke brugt javascript til at skifte states på links, alle states er kode op på standard  :hover, :active, :focus og :visited. Der findes også specifikke klasser, fx .link-focus, for at kunne vise staten på documentationsitet.

**Comment by jrmirland** [comment]
Hmm, det ser ud til, at jeg har været for hurtig der. Jeg kan ikke genskabe min observation :/ Beklager!
