### ISSUE TITLE
Link-farve er ikke tilgængelig

### ISSUE THREAD

**Issue by stil-ux-team** [FSGpilot/frontend-styleguide-components#5]
Den valgte link-farve #1b86c3 er ikke tilgængelig for mindre font-size som fx 14px. Man bør nok overveje at tone den til fx #187BB4, så font-size ikke er afgørende, men hvor der fortsat er lidt spillerum op til hover-farven.

**Comment by VirksDesignmanual** [comment]
Tak. Det får vi fikset.

**Comment by Kofoed** [comment]
Jeg har opdateret til #00f, så er der ingen ko på isen.
