### ISSUE TITLE
Underline i topmenu er ikke som USWD?

### ISSUE THREAD

**Issue by stil-ux-team** [FSGpilot/frontend-styleguide-components#7]
Et af de meget tydelige træk i USWDs topmenu (fx extended header, som STIL tager udgangspunkt i - og vist også Styleguiden?) er dens forskudte underline ved :hover på menupunkt. 

Jeg kan se i det nye design, at underline ikke længere følger linkets bredde ved markering, men nærmere dets "bounding box". Det vil sige, underline er breddere  - i eksemplet - end linket og dermed har en anden visuel karakter end USWD. Til gengæld ser det ud til, at underline følger linkets bredde i forbindelse med en dropdown menu.  Jeg synes, det vil give mening at beholde den opførsel, man har valgt i USWD.

**Comment by zumouxd** [comment]
Det bliver som USWDS i topmenuen.
