### ISSUE TITLE
IBMPlexSans-Bold.eot og andre filer mangler

### ISSUE THREAD

**Issue by AndersWinther-Dahl** [FSGpilot/frontend-styleguide-components#9]
Hej
Når jeg vil bygge min applikation hvor jeg har taget DKWDS 2.0.5 ind, får jeg en hel del fejl pga. referencer til filer, der ikke er der:
\fonts\IBMPlexSans\IBMPlexSans-Bold.eot
svg'er til fonte er der referencer til, men ingen svg'er i fonts/IBMPlexSans

ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader?{"ident":"postcss"}!./node_modules/dkwds/dist/css/dkwds-borgerdk.css
Module not found: Error: Can't resolve '../fonts/IBMPlexSans/IBMPlexSans-Bold.eot'

**Comment by emiljensengit** [comment]
Hej Anders, jeg ser på det og vender tilbage.

**Comment by emiljensengit** [comment]
Hej igen Anders, med den nye version (2.0.7) får jeg ikke nogen fejl ved download af font/svg'er. Sig endelig til hvis du stadig oplever fejl.

**Comment by AndersWinther-Dahl** [comment]
Jeg får stadig fejl om at IBMPlexSans-Bold.eot ikke er tilgængelig
Strukturen i DKWDS:
![image](https://user-images.githubusercontent.com/10073411/41040455-bf44d068-699c-11e8-8f19-b62cf86a0071.png)

**Comment by emiljensengit** [comment]
Ah my bad, fonten manglede faktisk helt fra repositoriet. Oprindeligt fik jeg ingen fejl da jeg testede ved at se i konsollen og ingen af de browsere jeg brugte beklagede sig over den manglede font. Men jeg gætter på at du bruger en bundler (webpack?) som checker for dette. Jeg har oploade en ny version med fonten.

**Comment by AndersWinther-Dahl** [comment]
Hej Emil
Ja, jeg bruger Anuglar CLI, som bruger Webpack.
Jeg får ikke længere fejl på eot-filen, men nu mangler der svg-filer til font'ene og andre billeder.
Har du mulighed for selv at køre webpack på det, så vi ikke skal ping-ponge?

**Comment by emiljensengit** [comment]
Hej Anders
Så har jeg fået opsat et webpack setup og har fået fixet de manglende filer. 
Jeg tilføjer webpack som et setup vi skal teste i når vi deployer så vi undgår manglende filer i fremtiden.

Jeg har testet med følgende scss setup i min main.scss fil:

$font-path:         '~dkwds/src/fonts/IBMPlexSans/';
$image-path:        '~dkwds/src/img';
$site-image-path:   '~dkwds/src/img';
$icons-folder-path: '~dkwds/src/img/svg-icons/';
@import "~dkwds/src/stylesheets/dkwds";

**Comment by AndersWinther-Dahl** [comment]
Super, nu kan jeg compile uden fejl :+1: 
Tak !
